### ISSUE TITLE
developing Language model regards  

### ISSUE THREAD

**Issue by AswiN-7** [balamurugan1603/balamurugan1603#2]
hi balamurugan 
i recently seen your hugging face profile 
im trying to create a roberta language model  for tamil
i have some doubts 
can you help me..

**Comment by balamurugan1603** [comment]
Ya sure. Sorry for the delayed reply, I didnt checked this issue.

**Comment by balamurugan1603** [comment]
@AswiN-7 I'm closing this issue as this is not relevant to this repository. If you want to contact me, connect with me via LinkedIn or send a mail to me.
